algo = input('Digite algo: ')
print('a variavel digitada é alpha? ', algo.isalpha())
print('a variavel digitada é numeric? ', algo.isnumeric())
print('a variavel digitada é alpha_numerico? ', algo.isalnum())
print('a variavel digitada é ascii? ', algo.isascii())
print('a variavel digitada é decimal? ', algo.isdecimal())
print('a variavel digitada é digit? ', algo.isdigit())
print('a variavel digitada é lower? ', algo.islower())
print('a variavel digitada é space? ', algo.isspace())
